spring.application.name=location_vehicule_projetG6
spring.datasource.url=jdbc:oracle:thin:@localhost:1550/siip
spring.datasource.username=PROJET_DEV_GROUPE_6
spring.datasource.password=GROUPE_6
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=9191
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database= oracle